### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'iterations'

### ISSUE THREAD

**Issue by botti007** [ernw/dizzy#2]
I tried to use this .dizz file to fuzz GTP:
https://github.com/ernw/dizzfiles/blob/master/gtp_v1/gtp_create_pdp_context_request.dizz
however i'am getting this error: 
ob/run: cmd was: './dizzy_cmd /root/dizzy/modules/demo/job/demo.conf'.
Traceback (most recent call last):
  File "/root/dizzy/./dizzy_cmd", line 102, in <module>
    main(False)
  File "/root/dizzy/./dizzy_cmd", line 84, in main
    j = Job(args.file, args.start_at, options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/dizzy/dizzy/job.py", line 112, in __init__
    self.mutations = self.act.iterations()
                     ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'iterations'

Could you help me ?

**Comment by 0xc0decafe** [comment]
Well.... the dizzfiles are written for dizzy-v1 and you try to run them with dizzy-v2. This is not gonna work (;
